# syntax=docker/dockerfile:1

FROM node:14 as build-stage

WORKDIR /app/hotel-room-tracker-new
COPY hotel-room-tracker-new/package*.json ./
RUN npm install

COPY hotel-room-tracker-new/ .
RUN npm run build

FROM nginx:alpine as production-stage
COPY --from=build-stage /app/hotel-room-tracker-new/dist/hotel-room-tracker-new /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
